apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: customer1-db
spec:
  instances: 3

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: customer1-db-credentials

  storage:
    size: 1Gi

  plugins:
        - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: customer1-objectstore

