apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: customer1-db-backup
spec:
  schedule: "0 0 10 * * *"
  backupOwnerReference: cluster
  cluster:
    name: customer1-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
